apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-m2s8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-m2s8
    app.kubernetes.io/part-of: e2e-golang
  name: devfile-sample-go-basic-m2s8
  namespace: e2e-demos-hsfe-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: devfile-sample-go-basic-m2s8
    weight: null
status: {}
